version: '3'
services:
  front:
    build: docker/front/
    volumes:
      - .:/var/www/lunch
    depends_on:
      - php
    ports:
      - '8969:80'

  php:
    build: docker/php
    volumes:
      - .:/var/www/lunch
    environment:
      - LUNCH_ENV