version: '3'
services:
  front:
    environment:
      - VIRTUAL_HOST=lunch.agares.info
  networks:
    - front_proxy_default
    - default
    restart: always
  
  db:
    restart: always

  php:
    restart: always

networks:
  frontproxy_default:
    external: true

