version: '3'
services:
  front:
    build: docker/front/
    volumes:
      - .:/var/www/lunch
    depends_on:
      - php
    ports:
      - '8969:80'

  php:
    build: docker/php
    volumes:
      - .:/var/www/lunch
    environment:
      - LUNCH_ENV
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - db

  db:
    build: docker/db/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./data/db:/var/lib/postgresql/data/